title: 王庆港
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/wangqinggang" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 王庆港 # add your name
author-img: william.jpg # add your photo
about-author: 计算机科学与技术学士、英语学士。我是一位大数据开发者，专注于大数据技术学习. Always hungry to keep learning. # add description
social-twitter: wangqinggang1 # add your Twitter handle
social-facebook: wangqinggang # add your Facebook handle
social-github: wangqinggang # add your Github handle
social-linkedin: wangqinggang # add your Linkedin handle
social-email: wqg599252594@gmail.com # add your Email address

# Disqus
discus-identifier: wangqinggang # add your discus identifier

# Tracker
analytics: wangqinggang # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
